Allow launching Phabricator Daemons individually.

diff --git a/templates/phd.erb b/templates/phd.erb
--- a/templates/phd.erb
+++ b/templates/phd.erb
@@ -34,6 +34,19 @@ case "$1" in
             *) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Failed to start
         esac
         ;;
+    launch)
+        i=2; while [ "$i" -le $# ]; do
+            [ "$VERBOSE" != no ] && log_daemon_msg "Launching $DESC" "$NAME" "$(eval echo \$$i)"
+            "$DAEMON" launch "$(eval echo \$$i)"
+            RETVAL="$?"
+            case "$?" in
+                0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                1) [ "$VERBOSE" != no ] && log_end_msg 255 ;; # Already started
+                *) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Failed to start
+            esac
+            i=$(($i+1))
+        done
+        ;;
     stop)
         [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
         "$DAEMON" stop
@@ -56,7 +69,7 @@ case "$1" in
         esac
         ;;
     *)
-        echo "Usage: /etc/init.d/$NAME {start|stop|status|restart}"
+        echo "Usage: /etc/init.d/$NAME {start|launch|stop|status|restart}"
         exit 1
         ;;
 esac
